// Auto-generated by @vesk/adapter

export async function GET(request) {
	const headers = Object.fromEntries(request.headers);
	return Response.json({
		message: 'Hello from Vesk API!',
		method: 'GET',
		url: request.url,
		headers,
	});
}

export async function POST(request) {
	const body = await request.json();
	return Response.json({ received: body, ok: true }, { status: 201 });
}

// ── Request handler wrapper ──
import { parseCookies } from '../runtime.js';

export async function handle(request) {
  const url = new URL(request.url);
  const urlParts = url.pathname.replace(/^\/api\/?/, '/').split('/').filter(Boolean);
  const method = request.method || 'GET';
  const params = {};

  const ctx = {
    headers: Object.fromEntries(request.headers.entries()),
    url: request.url,
    method,
    cookies: parseCookies(request.headers.get('cookie') || ''),
    locals: {},
  };
  Object.defineProperty(request, 'locals', {
    get: () => ctx.locals,
    enumerable: true,
  });

  const prev = globalThis.__vesk_request;
  globalThis.__vesk_request = ctx;
  try {
    const handler = { GET, POST }[method];
    if (!handler) {
      return new Response(JSON.stringify({ error: 'Method not allowed' }), {
        status: 405,
        headers: { 'Content-Type': 'application/json' },
      });
    }
    const response = await handler(request, { params: Promise.resolve(params) });
    if (response instanceof Response) return response;
    return new Response(JSON.stringify(response), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  } catch (e) {
    if (e.name === 'Redirect') {
      return new Response(null, { status: e.status || 302, headers: { Location: e.url } });
    }
    if (e.name === 'NotFoundError') {
      return new Response(JSON.stringify({ error: 'Not Found' }), { status: 404, headers: { 'Content-Type': 'application/json' } });
    }
    return new Response(JSON.stringify({ error: e.message }), { status: 500, headers: { 'Content-Type': 'application/json' } });
  } finally {
    globalThis.__vesk_request = prev;
  }
}
