import { CompletionItemKind } from 'vscode-languageserver/node.js';

// ── Intrinsics (auto-imported from @vesk/runtime) ─────────────

export const VESK_INTRINSICS: { name: string; kind: CompletionItemKind; detail: string; docs: string; insertText?: string; signature?: string }[] = [
  { name: 'track', kind: CompletionItemKind.Function, detail: 'Create a reactive signal', docs: 'Creates a reactive value. Returns a getter `fn()` that returns the value.', signature: 'track<T>(initial: T): [() => T, (v: T) => void]' },
  { name: 'get', kind: CompletionItemKind.Function, detail: 'Get reactive signal value', docs: 'Returns the current value of a reactive signal.', signature: 'get<T>(signal: () => T): T' },
  { name: 'set', kind: CompletionItemKind.Function, detail: 'Set reactive signal value', docs: 'Sets a new value on a reactive signal and triggers updates.', signature: 'set<T>(signal: (v: T) => void, value: T): void' },
  { name: 'derived', kind: CompletionItemKind.Function, detail: 'Create derived reactive value', docs: 'Creates a derived signal that recomputes when dependencies change.', signature: 'derived<T>(fn: () => T): () => T' },
  { name: 'effect', kind: CompletionItemKind.Function, detail: 'Run side effect on reactive changes', docs: 'Runs a function whenever its reactive dependencies change.', signature: 'effect(fn: () => void | (() => void)): () => void' },
  { name: 'root', kind: CompletionItemKind.Function, detail: 'Create reactive root scope', docs: 'Creates a root scope for reactive computations.', signature: 'root<T>(fn: () => T): T' },
  { name: 'untrack', kind: CompletionItemKind.Function, detail: 'Read signal without tracking', docs: 'Reads a signal value without creating a reactive dependency.', signature: 'untrack<T>(fn: () => T): T' },
  { name: 'peek', kind: CompletionItemKind.Function, detail: 'Alias for untrack', docs: 'Alias for untrack — reads without tracking.', signature: 'peek<T>(fn: () => T): T' },
  { name: 'tick', kind: CompletionItemKind.Function, detail: 'Flush pending updates', docs: 'Synchronously flushes all pending reactive updates.', signature: 'tick(): void' },
  { name: 'flushSync', kind: CompletionItemKind.Function, detail: 'Flush updates synchronously', docs: 'Runs a function and synchronously flushes all reactive updates.', signature: 'flushSync(fn: () => void): void' },
  { name: 'on_destroy', kind: CompletionItemKind.Function, detail: 'Register cleanup callback', docs: 'Registers a cleanup function called when the component is destroyed.', signature: 'on_destroy(fn: () => void): void' },
  { name: 'createContext', kind: CompletionItemKind.Function, detail: 'Create a context value', docs: 'Creates a context that can be provided/consumed by component trees.', signature: 'createContext<T>(defaultValue: T): Context<T>' },
  { name: 'Link', kind: CompletionItemKind.Class, detail: 'Client-side navigation link', docs: '<Link href="/path"> — SPA link component.', signature: 'Link(props: { href: string; class?: string; children?: unknown })' },
  { name: 'NavLink', kind: CompletionItemKind.Class, detail: 'Navigation link with active state', docs: '<NavLink href="/path" class="..." activeClass="..."> — link that highlights when active.', signature: 'NavLink(props: { href: string; class?: string; activeClass?: string; children?: unknown })' },
  { name: 'Outlet', kind: CompletionItemKind.Class, detail: 'Nested route outlet', docs: '<Outlet /> — renders matched child route.', signature: 'Outlet(props?: { children?: unknown })' },
  { name: 'useRouter', kind: CompletionItemKind.Function, detail: 'Access router instance', docs: 'Returns the router instance with navigate(), prefetch(), etc.', signature: 'useRouter(): { navigate: (path: string) => void; prefetch: (path: string) => void }' },
  { name: 'useNavigate', kind: CompletionItemKind.Function, detail: 'Navigate programmatically', docs: 'Returns a navigate function to programmatically navigate.', signature: 'useNavigate(): (path: string) => void' },
  { name: 'useParams', kind: CompletionItemKind.Function, detail: 'Access route parameters', docs: 'Returns the current route parameters object.', signature: 'useParams(): Record<string, string>' },
  { name: 'usePathname', kind: CompletionItemKind.Function, detail: 'Access current pathname', docs: 'Returns the current URL pathname as a reactive string.', signature: 'usePathname(): string' },
  { name: 'useSearchParams', kind: CompletionItemKind.Function, detail: 'Access search parameters', docs: 'Returns reactive search params with get/set/delete.', signature: 'useSearchParams(): URLSearchParams' },
  { name: 'useFetch', kind: CompletionItemKind.Function, detail: 'Data fetching with SSR support', docs: 'useFetch(url) — fetches data with SSR hydration support.', signature: 'useFetch<T>(url: string, init?: RequestInit): { data: T | null; error: Error | null; loading: boolean }' },
  { name: 'Form', kind: CompletionItemKind.Class, detail: 'SSR-first form component', docs: '<Form action="/api/submit" onSubmit={...}> — validates and submits forms.', signature: 'Form(props: { action: string; onSubmit?: (data: FormData) => void; children?: unknown })' },
  { name: 'Field', kind: CompletionItemKind.Class, detail: 'Form field with validation', docs: '<Field name="email" required email> — form field with validation display.', signature: 'Field(props: { name: string; required?: boolean; children?: unknown })' },
  { name: 'required', kind: CompletionItemKind.Function, detail: 'Validation: required', docs: 'required("Custom message?") — validates value is non-empty.', signature: 'required(message?: string): Validator' },
  { name: 'email', kind: CompletionItemKind.Function, detail: 'Validation: email format', docs: 'email("Custom message?") — validates email format.', signature: 'email(message?: string): Validator' },
  { name: 'minLength', kind: CompletionItemKind.Function, detail: 'Validation: minimum length', docs: 'minLength(3, "Custom message?") — validates minimum string length.', signature: 'minLength(min: number, message?: string): Validator' },
  { name: 'maxLength', kind: CompletionItemKind.Function, detail: 'Validation: maximum length', docs: 'maxLength(100, "Custom message?") — validates maximum string length.', signature: 'maxLength(max: number, message?: string): Validator' },
  { name: 'pattern', kind: CompletionItemKind.Function, detail: 'Validation: regex pattern', docs: 'pattern(/^[a-z]+$/, "Custom message?") — validates against regex.', signature: 'pattern(re: RegExp, message?: string): Validator' },
  { name: 'custom', kind: CompletionItemKind.Function, detail: 'Custom validation', docs: 'custom(fn, "Message") — custom validation function.', signature: 'custom(fn: (value: unknown) => boolean, message?: string): Validator' },
  { name: 'Experiment', kind: CompletionItemKind.Class, detail: 'A/B testing component', docs: '<Experiment name="test" variants={[...]}> — A/B test variants.', signature: 'Experiment(props: { name: string; variants: string[]; children?: unknown })' },
  { name: 'Image', kind: CompletionItemKind.Class, detail: 'Optimized image component', docs: '<Image src="/photo.jpg" width={800} height={600} /> — responsive, lazy images.', signature: 'Image(props: { src: string; width?: number; height?: number; alt?: string })' },
  { name: 'JsonLd', kind: CompletionItemKind.Class, detail: 'JSON-LD structured data', docs: '<JsonLd schema={ArticleSchema({...})} /> — injects structured data.', signature: 'JsonLd(props: { schema: Record<string, unknown> })' },
  { name: 'Portal', kind: CompletionItemKind.Class, detail: 'Portal to another DOM node', docs: '<Portal container={document.body}>content</Portal>.', signature: 'Portal(props: { container: HTMLElement; children?: unknown })' },
  { name: 'Head', kind: CompletionItemKind.Class, detail: 'Document head element', docs: '<Head><title>...</title><meta ...></Head> — injects into <head>.', signature: 'Head(props: { children?: unknown })' },
  { name: 'slot', kind: CompletionItemKind.Keyword, detail: 'Component slot for children', docs: '<slot /> — renders children passed to the component.', signature: 'slot(props?: { name?: string; children?: unknown })' },
  { name: 'reconcile', kind: CompletionItemKind.Function, detail: 'Array reconciliation', docs: 'reconcile(arr, key) — efficient list diffing.', signature: 'reconcile<T>(arr: T[], key: keyof T): T[]' },
  { name: 'redirect', kind: CompletionItemKind.Function, detail: 'Redirect to another route', docs: 'redirect("/path") — throws a redirect.', signature: 'redirect(path: string): never' },
  { name: 'permanentRedirect', kind: CompletionItemKind.Function, detail: 'Permanent redirect (301)', docs: 'permanentRedirect("/path") — throws a permanent redirect.', signature: 'permanentRedirect(path: string): never' },
  { name: 'notFound', kind: CompletionItemKind.Function, detail: 'Throw 404', docs: 'notFound() — throws a not-found response.', signature: 'notFound(): never' },
];

// ── Tailwind CSS classes (comprehensive subset) ────────────────

export const TAILWIND_CLASSES = [
  // Layout
  'container', 'block', 'inline-block', 'inline', 'flex', 'inline-flex', 'grid', 'inline-grid',
  'table', 'table-row', 'table-cell', 'hidden', 'flow-root', 'contents',
  // Flexbox
  'flex-row', 'flex-row-reverse', 'flex-col', 'flex-col-reverse', 'flex-wrap', 'flex-nowrap',
  'flex-1', 'flex-auto', 'flex-initial', 'flex-none', 'grow', 'grow-0', 'shrink', 'shrink-0',
  'justify-start', 'justify-end', 'justify-center', 'justify-between', 'justify-around', 'justify-evenly',
  'items-start', 'items-end', 'items-center', 'items-baseline', 'items-stretch',
  'content-start', 'content-end', 'content-center', 'content-between', 'content-around',
  'self-start', 'self-end', 'self-center', 'self-stretch', 'self-baseline',
  // Grid
  'grid-cols-1', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4', 'grid-cols-5', 'grid-cols-6',
  'grid-cols-7', 'grid-cols-8', 'grid-cols-9', 'grid-cols-10', 'grid-cols-11', 'grid-cols-12',
  'grid-cols-none', 'col-span-1', 'col-span-2', 'col-span-3', 'col-span-4', 'col-span-5', 'col-span-6',
  'col-span-full', 'col-start-1', 'col-end-1',
  'grid-rows-1', 'grid-rows-2', 'grid-rows-3', 'grid-rows-4', 'grid-rows-5', 'grid-rows-6',
  'row-span-1', 'row-span-2', 'row-span-3', 'row-span-full',
  'gap-0', 'gap-1', 'gap-2', 'gap-3', 'gap-4', 'gap-5', 'gap-6', 'gap-8', 'gap-10', 'gap-12',
  'gap-x-0', 'gap-x-1', 'gap-x-2', 'gap-x-4', 'gap-x-8',
  'gap-y-0', 'gap-y-1', 'gap-y-2', 'gap-y-4', 'gap-y-8',
  // Spacing
  'p-0', 'p-1', 'p-2', 'p-3', 'p-4', 'p-5', 'p-6', 'p-8', 'p-10', 'p-12', 'p-16', 'p-20', 'p-24',
  'px-0', 'px-1', 'px-2', 'px-3', 'px-4', 'px-5', 'px-6', 'px-8', 'px-10',
  'py-0', 'py-1', 'py-2', 'py-3', 'py-4', 'py-5', 'py-6', 'py-8', 'py-10',
  'pt-0', 'pt-1', 'pt-2', 'pt-3', 'pt-4', 'pt-5', 'pt-6', 'pt-8',
  'pb-0', 'pb-1', 'pb-2', 'pb-3', 'pb-4', 'pb-5', 'pb-6', 'pb-8',
  'pl-0', 'pl-1', 'pl-2', 'pl-3', 'pl-4', 'pl-5', 'pl-6', 'pl-8',
  'pr-0', 'pr-1', 'pr-2', 'pr-3', 'pr-4', 'pr-5', 'pr-6', 'pr-8',
  'm-0', 'm-1', 'm-2', 'm-3', 'm-4', 'm-5', 'm-6', 'm-8', 'm-10', 'm-12', 'm-16', 'm-20', 'm-auto',
  'mx-0', 'mx-1', 'mx-2', 'mx-3', 'mx-4', 'mx-5', 'mx-6', 'mx-8', 'mx-auto',
  'my-0', 'my-1', 'my-2', 'my-3', 'my-4', 'my-5', 'my-6', 'my-8', 'my-auto',
  'mt-0', 'mt-1', 'mt-2', 'mt-3', 'mt-4', 'mt-5', 'mt-6', 'mt-8', 'mt-auto',
  'mb-0', 'mb-1', 'mb-2', 'mb-3', 'mb-4', 'mb-5', 'mb-6', 'mb-8', 'mb-auto',
  'ml-0', 'ml-1', 'ml-2', 'ml-3', 'ml-4', 'ml-auto',
  'mr-0', 'mr-1', 'mr-2', 'mr-3', 'mr-4', 'mr-auto',
  'space-x-0', 'space-x-1', 'space-x-2', 'space-x-3', 'space-x-4', 'space-x-8',
  'space-y-0', 'space-y-1', 'space-y-2', 'space-y-3', 'space-y-4', 'space-y-8',
  // Sizing
  'w-0', 'w-1', 'w-2', 'w-3', 'w-4', 'w-5', 'w-6', 'w-8', 'w-10', 'w-12', 'w-16', 'w-20', 'w-24',
  'w-32', 'w-40', 'w-48', 'w-56', 'w-64', 'w-auto', 'w-1/2', 'w-1/3', 'w-2/3', 'w-1/4', 'w-3/4',
  'w-full', 'w-screen', 'w-min', 'w-max', 'w-fit',
  'h-0', 'h-1', 'h-2', 'h-3', 'h-4', 'h-5', 'h-6', 'h-8', 'h-10', 'h-12', 'h-16', 'h-20', 'h-24',
  'h-auto', 'h-1/2', 'h-1/3', 'h-2/3', 'h-1/4', 'h-3/4', 'h-full', 'h-screen', 'h-min', 'h-max', 'h-fit',
  'min-w-0', 'min-w-full', 'min-w-min', 'min-w-max',
  'min-h-0', 'min-h-full', 'min-h-screen',
  'max-w-0', 'max-w-none', 'max-w-xs', 'max-w-sm', 'max-w-md', 'max-w-lg', 'max-w-xl', 'max-w-2xl',
  'max-w-3xl', 'max-w-4xl', 'max-w-5xl', 'max-w-6xl', 'max-w-7xl', 'max-w-full', 'max-w-screen-xl',
  'max-h-0', 'max-h-full', 'max-h-screen',
  // Typography
  'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl', 'text-4xl',
  'text-5xl', 'text-6xl', 'text-7xl', 'text-8xl', 'text-9xl',
  'font-thin', 'font-extralight', 'font-light', 'font-normal', 'font-medium', 'font-semibold',
  'font-bold', 'font-extrabold', 'font-black',
  'text-left', 'text-center', 'text-right', 'text-justify', 'text-start', 'text-end',
  'italic', 'not-italic', 'underline', 'line-through', 'no-underline', 'overline',
  'uppercase', 'lowercase', 'capitalize', 'normal-case',
  'leading-none', 'leading-tight', 'leading-snug', 'leading-normal', 'leading-relaxed', 'leading-loose',
  'tracking-tighter', 'tracking-tight', 'tracking-normal', 'tracking-wide', 'tracking-wider', 'tracking-widest',
  'whitespace-normal', 'whitespace-nowrap', 'whitespace-pre', 'whitespace-pre-line', 'whitespace-pre-wrap',
  'break-normal', 'break-words', 'break-all', 'truncate',
  'list-none', 'list-disc', 'list-decimal', 'list-inside', 'list-outside',
  // Backgrounds
  'bg-transparent', 'bg-black', 'bg-white', 'bg-gray-50', 'bg-gray-100', 'bg-gray-200',
  'bg-gray-300', 'bg-gray-400', 'bg-gray-500', 'bg-gray-600', 'bg-gray-700', 'bg-gray-800', 'bg-gray-900',
  'bg-red-50', 'bg-red-100', 'bg-red-200', 'bg-red-500', 'bg-red-600', 'bg-red-700',
  'bg-blue-50', 'bg-blue-100', 'bg-blue-200', 'bg-blue-500', 'bg-blue-600', 'bg-blue-700',
  'bg-green-50', 'bg-green-100', 'bg-green-200', 'bg-green-500', 'bg-green-600', 'bg-green-700',
  'bg-yellow-50', 'bg-yellow-100', 'bg-yellow-200', 'bg-yellow-500', 'bg-yellow-600',
  'bg-purple-50', 'bg-purple-100', 'bg-purple-500', 'bg-purple-600',
  'bg-cover', 'bg-contain', 'bg-center', 'bg-top', 'bg-bottom', 'bg-no-repeat', 'bg-repeat',
  // Borders
  'border', 'border-0', 'border-2', 'border-4', 'border-8',
  'border-t', 'border-b', 'border-l', 'border-r', 'border-x', 'border-y',
  'border-transparent', 'border-black', 'border-white',
  'border-gray-100', 'border-gray-200', 'border-gray-300', 'border-gray-400', 'border-gray-500',
  'border-red-500', 'border-blue-500', 'border-green-500',
  'rounded-none', 'rounded-sm', 'rounded', 'rounded-md', 'rounded-lg', 'rounded-xl', 'rounded-2xl',
  'rounded-3xl', 'rounded-full',
  'rounded-t', 'rounded-b', 'rounded-l', 'rounded-r',
  // Effects
  'shadow-sm', 'shadow', 'shadow-md', 'shadow-lg', 'shadow-xl', 'shadow-2xl', 'shadow-none',
  'opacity-0', 'opacity-5', 'opacity-10', 'opacity-25', 'opacity-50', 'opacity-75', 'opacity-100',
  // Transitions
  'transition', 'transition-none', 'transition-all', 'transition-colors', 'transition-opacity',
  'transition-shadow', 'transition-transform',
  'duration-75', 'duration-100', 'duration-150', 'duration-200', 'duration-300', 'duration-500',
  'ease-linear', 'ease-in', 'ease-out', 'ease-in-out',
  // Transform
  'scale-0', 'scale-50', 'scale-75', 'scale-90', 'scale-95', 'scale-100', 'scale-105', 'scale-110',
  'rotate-0', 'rotate-45', 'rotate-90', 'rotate-180',
  'translate-x-0', 'translate-x-1', 'translate-x-2', 'translate-x-3', 'translate-x-4',
  'translate-y-0', 'translate-y-1', 'translate-y-2', 'translate-y-3', 'translate-y-4',
  // Interactivity
  'cursor-pointer', 'cursor-default', 'cursor-not-allowed', 'cursor-wait', 'cursor-text',
  'select-none', 'select-text', 'select-all', 'select-auto',
  'resize-none', 'resize', 'resize-y', 'resize-x',
  'pointer-events-none', 'pointer-events-auto',
  // Position
  'static', 'fixed', 'absolute', 'relative', 'sticky',
  'inset-0', 'inset-x-0', 'inset-y-0',
  'top-0', 'right-0', 'bottom-0', 'left-0',
  'z-0', 'z-10', 'z-20', 'z-30', 'z-40', 'z-50', 'z-auto',
  // Overflow
  'overflow-auto', 'overflow-hidden', 'overflow-visible', 'overflow-scroll',
  'overflow-x-auto', 'overflow-y-auto',
  'overscroll-auto', 'overscroll-contain', 'overscroll-none',
];

// ── HTML elements ──────────────────────────────────────────────

export const HTML_ELEMENTS = [
  'a', 'abbr', 'address', 'area', 'article', 'aside', 'audio',
  'b', 'base', 'bdi', 'bdo', 'blockquote', 'body', 'br', 'button',
  'canvas', 'caption', 'cite', 'code', 'col', 'colgroup',
  'data', 'datalist', 'dd', 'del', 'details', 'dfn', 'dialog', 'div', 'dl', 'dt',
  'em', 'embed',
  'fieldset', 'figcaption', 'figure', 'footer', 'form',
  'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'head', 'header', 'hgroup', 'hr', 'html',
  'i', 'iframe', 'img', 'input', 'ins',
  'kbd',
  'label', 'legend', 'li', 'link',
  'main', 'map', 'mark', 'menu', 'meta', 'meter',
  'nav', 'noscript',
  'object', 'ol', 'optgroup', 'option', 'output',
  'p', 'picture', 'portal', 'pre', 'progress',
  'q',
  'rp', 'rt', 'ruby',
  's', 'samp', 'script', 'section', 'select', 'slot', 'small', 'source', 'span', 'strong', 'style', 'sub', 'summary', 'sup',
  'table', 'tbody', 'td', 'template', 'textarea', 'tfoot', 'th', 'thead', 'time', 'title', 'tr', 'track',
  'u', 'ul',
  'var', 'video',
  'wbr',
];

export const VOID_ELEMENTS = new Set([
  'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr',
]);

export const HTML_ELEMENT_DOCS: Record<string, string> = {
  a: 'Hyperlink. Use `href` for the target URL and `download` to force download.',
  abbr: 'Abbreviation or acronym, with a `title` attribute explaining the full term.',
  address: 'Contact information for the nearest article or body ancestor.',
  area: 'Clickable region inside an image map (`<map>`).',
  article: 'Self-contained composition (blog post, forum post, news article).',
  aside: 'Sidebar content tangentially related to the main content.',
  audio: 'Embedded sound content with playback controls.',
  b: 'Bold text (presentational; prefer `<strong>` for importance).',
  base: 'Base URL and default target for relative links. Only valid in `<head>`.',
  bdi: 'Bidirectional isolation — text with an unknown directionality.',
  bdo: 'Overrides text direction (`dir="rtl"` / `dir="ltr"`).',
  blockquote: 'Quoted content. Use `cite` for the source URL.',
  body: 'Document body — the visible content container.',
  br: 'Line break. Void element.',
  button: 'Clickable button. `type` is "submit", "reset" or "button".',
  canvas: 'Drawing surface for 2D/3D graphics via script.',
  caption: 'Title of a table column group (`<colgroup>`) or table.',
  cite: 'Title of a creative work (book, film, paper).',
  code: 'Inline fragment of computer code.',
  col: 'Column in a `<colgroup>`, sharing column-wide attributes.',
  colgroup: 'Group of columns within a table.',
  data: 'Machine-readable value with a human-readable `value` attribute.',
  datalist: 'Set of `<option>` suggestions for an `<input list="...">`.',
  dd: 'Description / value of a `<dt>` term in a `<dl>` list.',
  del: 'Deleted (removed) text.',
  details: 'Disclosure widget that can be expanded/collapsed.',
  dfn: 'Term being defined within the document.',
  dialog: 'Modal or non-modal dialog box.',
  div: 'Generic block-level container with no semantic meaning.',
  dl: 'Description list: `<dt>` terms and `<dd>` descriptions.',
  dt: 'Term / name inside a `<dl>` description list.',
  em: 'Emphasized text (typically rendered italic).',
  embed: 'Embedded external content (plug-in based). Void element.',
  fieldset: 'Group of form controls with an optional `<legend>`.',
  figcaption: 'Caption describing a `<figure>`.',
  figure: 'Self-contained content with an optional `<figcaption>`.',
  footer: 'Footer for the nearest sectioning content or root.',
  form: 'Interactive form. `action`, `method`, `enctype` control submission.',
  h1: 'Top-level section heading.',
  h2: 'Second-level section heading.',
  h3: 'Third-level section heading.',
  h4: 'Fourth-level section heading.',
  h5: 'Fifth-level section heading.',
  h6: 'Sixth-level section heading.',
  head: 'Document metadata container. Not rendered directly.',
  header: 'Introductory or navigational header for a section.',
  hgroup: 'Group of headings.',
  hr: 'Thematic break between sections. Void element.',
  html: 'Root element of an HTML document.',
  i: 'Idiomatic text (typically rendered italic; icon glyph).',
  iframe: 'Nested browsing context (embedded frame).',
  img: 'Embedded image. `src` and `alt` are required. Void element.',
  input: 'Interactive form control accepting user data. Void element.',
  ins: 'Inserted (added) text.',
  kbd: 'Keyboard input the user should press.',
  label: 'Caption for a form control. Clicking focuses the control.',
  legend: 'Caption for a `<fieldset>`.',
  li: 'List item inside `<ul>`, `<ol>` or `<menu>`.',
  link: 'External resource link (stylesheets, icons). Void element, in `<head>`.',
  main: 'Dominant content of the document. One per page.',
  map: 'Image map with clickable `<area>` regions.',
  mark: 'Highlighted text for reference/notation.',
  menu: 'Menu of commands (toolbar context).',
  meta: 'Machine-readable document metadata. Void element, in `<head>`.',
  meter: 'Scalar measurement within a known range (`min`, `max`, `value`).',
  nav: 'Major navigation block.',
  noscript: 'Content shown when scripts are disabled.',
  object: 'External resource (image, PDF, plug-in) as embedded content.',
  ol: 'Ordered (numbered) list.',
  optgroup: 'Group of `<option>` elements inside a `<select>`.',
  option: 'Single choice inside `<select>`, `<optgroup>` or `<datalist>`.',
  output: 'Result of a calculation or user action.',
  p: 'Paragraph of text.',
  picture: 'Multiple `<source>` images with an `<img>` fallback.',
  pre: 'Preformatted text (whitespace preserved, monospace).',
  progress: 'Progress indicator (`max`, `value`).',
  q: 'Short inline quotation.',
  rp: 'Fallback parentheses for ruby annotations.',
  rt: 'Ruby text (pronunciation) annotation.',
  ruby: 'Ruby annotation for East-Asian text.',
  s: 'Text no longer accurate (struck through).',
  samp: 'Sample output from a program.',
  script: 'Embedded or external JavaScript.',
  section: 'Thematic grouping of content, usually with a heading.',
  select: 'Dropdown selection control with `<option>` children.',
  slot: 'Web component placeholder for distributable content.',
  small: 'Side comment / fine print (typically smaller text).',
  source: 'Media resource for `<picture>`, `<audio>` or `<video>`. Void element.',
  span: 'Generic inline container with no semantic meaning.',
  strong: 'Text of strong importance (typically rendered bold).',
  style: 'Embedded CSS for the document.',
  sub: 'Subscript text.',
  summary: 'Disclosure widget label for `<details>`.',
  sup: 'Superscript text.',
  table: 'Two-dimensional data table.',
  tbody: 'Body rows group of a table.',
  td: 'Table data cell.',
  template: 'Inert document fragment cloned at runtime.',
  textarea: 'Multi-line plain-text editing control.',
  tfoot: 'Footer rows group of a table.',
  th: 'Table header cell. `scope` defines which cells it heads.',
  thead: 'Header rows group of a table.',
  time: 'Machine-readable time/date (`datetime`).',
  title: 'Document title. In `<head>`.',
  tr: 'Table row.',
  u: 'Unarticulated annotation (typically underlined).',
  ul: 'Unordered (bulleted) list.',
  var: 'Variable in mathematical or programming context.',
  video: 'Embedded video with `src` and optional `<source>` children.',
  wbr: 'Optional line-break opportunity. Void element.',
};

// ── Event handlers ─────────────────────────────────────────────

export const EVENT_HANDLERS: Record<string, string> = {
  onClick: 'Fires when the element is clicked. Pass an arrow function: `onClick={() => set(1)}`.',
  onDoubleClick: 'Fires when the element is double-clicked.',
  onChange: 'Fires when the value of an `<input>`, `<select>` or `<textarea>` changes.',
  onInput: 'Fires when an input value is entered. Fires on every keystroke.',
  onSubmit: 'Fires when a form is submitted. Prevent default with `e.preventDefault()`.',
  onFocus: 'Fires when an element receives focus.',
  onBlur: 'Fires when an element loses focus.',
  onKeyDown: 'Fires when a key is pressed down.',
  onKeyUp: 'Fires when a key is released.',
  onKeyPress: 'Fires when a character key is pressed.',
  onMouseDown: 'Fires when a mouse button is pressed down on the element.',
  onMouseUp: 'Fires when a mouse button is released.',
  onMouseMove: 'Fires when the pointer moves over the element.',
  onMouseOver: 'Fires when the pointer enters the element.',
  onMouseOut: 'Fires when the pointer leaves the element.',
  onMouseEnter: 'Fires when the pointer enters the element. Does not bubble.',
  onMouseLeave: 'Fires when the pointer leaves the element. Does not bubble.',
  onScroll: 'Fires when the element is scrolled.',
  onWheel: 'Fires when the mouse wheel is rotated.',
  onTouchStart: 'Fires when a touch point is placed on the element.',
  onTouchEnd: 'Fires when a touch point is removed.',
  onTouchMove: 'Fires when a touch point moves across the element.',
  onLoad: 'Fires when the resource (e.g. `<img>`, `<iframe>`) has loaded.',
  onError: 'Fires when a resource fails to load.',
  onContextMenu: 'Fires when the right-click context menu is requested.',
  onDrag: 'Fires during a drag operation.',
  onDragStart: 'Fires when a drag operation starts.',
  onDragEnd: 'Fires when a drag operation ends.',
  onDragOver: 'Fires when an element is dragged over a valid target.',
  onDrop: 'Fires when an element is dropped on a valid target.',
  onPaste: 'Fires when pasting from the clipboard.',
  onCopy: 'Fires when copying to the clipboard.',
  onCut: 'Fires when cutting to the clipboard.',
};

export const EVENT_HANDLER_NAMES = Object.keys(EVENT_HANDLERS);

// ── HTML attributes ────────────────────────────────────────────

export const GLOBAL_HTML_ATTRIBUTES = [
  'class', 'className', 'id', 'style', 'title', 'lang', 'dir', 'hidden', 'tabindex',
  'role', 'aria-label', 'aria-hidden', 'aria-expanded', 'aria-checked', 'aria-describedby',
  'data-id', 'spellcheck', 'autofocus', 'draggable', 'contenteditable',
];

export const TAG_SPECIFIC_ATTRIBUTES: Record<string, string[]> = {
  a: ['href', 'target', 'rel', 'download', 'hreflang'],
  img: ['src', 'alt', 'width', 'height', 'loading', 'srcset', 'sizes', 'decoding'],
  input: ['type', 'name', 'value', 'placeholder', 'disabled', 'readonly', 'required', 'checked', 'maxlength', 'minlength', 'pattern', 'min', 'max', 'step', 'autocomplete'],
  textarea: ['name', 'value', 'placeholder', 'rows', 'cols', 'disabled', 'readonly', 'required', 'maxlength'],
  select: ['name', 'value', 'multiple', 'disabled', 'required', 'autocomplete'],
  option: ['value', 'disabled', 'selected', 'label'],
  form: ['action', 'method', 'enctype', 'target', 'novalidate', 'name'],
  button: ['type', 'name', 'value', 'disabled'],
  label: ['for'],
  meta: ['name', 'content', 'charset', 'http-equiv', 'property'],
  link: ['href', 'rel', 'type', 'media', 'sizes'],
  script: ['src', 'type', 'async', 'defer', 'defer'],
  style: ['type', 'media'],
  iframe: ['src', 'width', 'height', 'title', 'allow', 'loading', 'sandbox'],
  video: ['src', 'poster', 'controls', 'width', 'height', 'autoplay', 'muted', 'loop', 'preload'],
  audio: ['src', 'controls', 'autoplay', 'muted', 'loop', 'preload'],
  source: ['src', 'srcset', 'type', 'media', 'sizes'],
  table: ['border', 'cellspacing', 'cellpadding'],
  td: ['colspan', 'rowspan', 'headers', 'scope'],
  th: ['colspan', 'rowspan', 'scope', 'abbr'],
  svg: ['viewBox', 'fill', 'stroke', 'width', 'height', 'xmlns'],
};

// ── Runtime function signatures (for signature help) ──────────

export const RUNTIME_SIGNATURES: Record<string, { label: string; params: { label: string; docs: string }[]; docs: string }> = {
  track: {
    label: 'track(value)',
    params: [{ label: 'value', docs: 'Initial value, or a function to lazily compute the value.' }],
    docs: 'Creates a reactive value. Returns a getter function; with `let &[x] = track(v)` the binding `x` stays in sync.',
  },
  derived: {
    label: 'derived(fn)',
    params: [{ label: 'fn', docs: 'Pure function that reads reactive getters and returns a computed value.' }],
    docs: 'Creates a derived signal that recomputes when its reactive dependencies change.',
  },
  effect: {
    label: 'effect(fn)',
    params: [{ label: 'fn', docs: 'Side-effect function that runs whenever its reactive dependencies change.' }],
    docs: 'Runs a function whenever its reactive dependencies change.',
  },
  get: {
    label: 'get(signal)',
    params: [{ label: 'signal', docs: 'The reactive signal to read.' }],
    docs: 'Returns the current value of a reactive signal.',
  },
  set: {
    label: 'set(signal, value)',
    params: [
      { label: 'signal', docs: 'The reactive signal to update.' },
      { label: 'value', docs: 'The new value, or an updater function `(prev) => next`.' },
    ],
    docs: 'Sets a new value on a reactive signal and triggers updates.',
  },
  root: {
    label: 'root(fn)',
    params: [{ label: 'fn', docs: 'Function that creates reactive computations inside a new owner scope.' }],
    docs: 'Creates a root scope for reactive computations.',
  },
  useFetch: {
    label: 'useFetch(url)',
    params: [{ label: 'url', docs: 'URL to fetch. Supports SSR preloads.' }],
    docs: 'Fetches data with SSR hydration support.',
  },
  useNavigate: {
    label: 'useNavigate()',
    params: [],
    docs: 'Returns a navigate function to programmatically navigate.',
  },
  useParams: {
    label: 'useParams()',
    params: [],
    docs: 'Returns the current route parameters object.',
  },
  usePathname: {
    label: 'usePathname()',
    params: [],
    docs: 'Returns the current URL pathname as a reactive string.',
  },
  useSearchParams: {
    label: 'useSearchParams()',
    params: [],
    docs: 'Returns reactive search params with get/set/delete.',
  },
  required: {
    label: 'required(message?)',
    params: [{ label: 'message', docs: 'Optional custom error message.' }],
    docs: 'Validates that a form value is non-empty.',
  },
  email: {
    label: 'email(message?)',
    params: [{ label: 'message', docs: 'Optional custom error message.' }],
    docs: 'Validates an email format.',
  },
  minLength: {
    label: 'minLength(n, message?)',
    params: [
      { label: 'n', docs: 'Minimum length.' },
      { label: 'message', docs: 'Optional custom error message.' },
    ],
    docs: 'Validates minimum string length.',
  },
  maxLength: {
    label: 'maxLength(n, message?)',
    params: [
      { label: 'n', docs: 'Maximum length.' },
      { label: 'message', docs: 'Optional custom error message.' },
    ],
    docs: 'Validates maximum string length.',
  },
  pattern: {
    label: 'pattern(regex, message?)',
    params: [
      { label: 'regex', docs: 'Regular expression to test against.' },
      { label: 'message', docs: 'Optional custom error message.' },
    ],
    docs: 'Validates a value against a regex.',
  },
  custom: {
    label: 'custom(fn, message)',
    params: [
      { label: 'fn', docs: 'Custom validation function returning a boolean or string.' },
      { label: 'message', docs: 'Error message shown when validation fails.' },
    ],
    docs: 'Custom validation function.',
  },
  redirect: {
    label: 'redirect(path)',
    params: [{ label: 'path', docs: 'Path to redirect to (temporary 307).' }],
    docs: 'Throws a redirect response.',
  },
  permanentRedirect: {
    label: 'permanentRedirect(path)',
    params: [{ label: 'path', docs: 'Path to redirect to (permanent 301).' }],
    docs: 'Throws a permanent redirect response.',
  },
  notFound: {
    label: 'notFound()',
    params: [],
    docs: 'Throws a 404 not-found response.',
  },
};

// ── CSS knowledge ───────────────────────────────────────────────

export const CSS_PROPERTIES: Record<string, { values: string[], description: string }> = {
  'color': { values: ['inherit', 'initial', 'transparent', 'currentColor'], description: 'Text color' },
  'background-color': { values: ['inherit', 'initial', 'transparent'], description: 'Background color' },
  'background': { values: ['inherit', 'initial', 'none', 'transparent'], description: 'Background shorthand' },
  'background-image': { values: ['none', 'inherit', 'initial'], description: 'Background image' },
  'background-size': { values: ['auto', 'cover', 'contain', 'inherit'], description: 'Background size' },
  'background-position': { values: ['center', 'top', 'bottom', 'left', 'right', 'inherit'], description: 'Background position' },
  'background-repeat': { values: ['repeat', 'no-repeat', 'repeat-x', 'repeat-y', 'inherit'], description: 'Background repeat' },
  'margin': { values: ['auto', 'inherit', 'initial'], description: 'Margin shorthand' },
  'margin-top': { values: ['auto', 'inherit'], description: 'Margin top' },
  'margin-right': { values: ['auto', 'inherit'], description: 'Margin right' },
  'margin-bottom': { values: ['auto', 'inherit'], description: 'Margin bottom' },
  'margin-left': { values: ['auto', 'inherit'], description: 'Margin left' },
  'padding': { values: ['inherit', 'initial'], description: 'Padding shorthand' },
  'padding-top': { values: ['inherit'], description: 'Padding top' },
  'padding-right': { values: ['inherit'], description: 'Padding right' },
  'padding-bottom': { values: ['inherit'], description: 'Padding bottom' },
  'padding-left': { values: ['inherit'], description: 'Padding left' },
  'width': { values: ['auto', 'inherit', 'initial', '100%', '100vw', 'fit-content', 'max-content', 'min-content'], description: 'Width' },
  'height': { values: ['auto', 'inherit', 'initial', '100%', '100vh', 'fit-content', 'max-content', 'min-content'], description: 'Height' },
  'min-width': { values: ['auto', 'inherit', 'initial'], description: 'Minimum width' },
  'min-height': { values: ['auto', 'inherit', 'initial'], description: 'Minimum height' },
  'max-width': { values: ['none', 'inherit', 'initial'], description: 'Maximum width' },
  'max-height': { values: ['none', 'inherit', 'initial'], description: 'Maximum height' },
  'display': { values: ['block', 'inline', 'inline-flex', 'flex', 'inline-flex', 'grid', 'inline-grid', 'none', 'contents', 'table', 'flow-root', 'inherit'], description: 'Display type' },
  'position': { values: ['static', 'relative', 'absolute', 'fixed', 'sticky', 'inherit'], description: 'Positioning' },
  'top': { values: ['auto', 'inherit', 'initial'], description: 'Top offset' },
  'right': { values: ['auto', 'inherit', 'initial'], description: 'Right offset' },
  'bottom': { values: ['auto', 'inherit', 'initial'], description: 'Bottom offset' },
  'left': { values: ['auto', 'inherit', 'initial'], description: 'Left offset' },
  'flex-direction': { values: ['row', 'row-reverse', 'column', 'column-reverse', 'inherit'], description: 'Flex direction' },
  'flex-wrap': { values: ['nowrap', 'wrap', 'wrap-reverse', 'inherit'], description: 'Flex wrap' },
  'flex': { values: ['none', 'auto', 'inherit', 'initial'], description: 'Flex shorthand' },
  'flex-grow': { values: ['0', '1', 'inherit'], description: 'Flex grow factor' },
  'flex-shrink': { values: ['0', '1', 'inherit'], description: 'Flex shrink factor' },
  'flex-basis': { values: ['auto', '0', '100%', 'inherit'], description: 'Flex basis' },
  'justify-content': { values: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly', 'inherit'], description: 'Justify content' },
  'align-items': { values: ['flex-start', 'flex-end', 'center', 'baseline', 'stretch', 'inherit'], description: 'Align items' },
  'align-self': { values: ['auto', 'flex-start', 'flex-end', 'center', 'baseline', 'stretch', 'inherit'], description: 'Align self' },
  'align-content': { values: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'stretch', 'inherit'], description: 'Align content' },
  'gap': { values: ['normal', 'inherit'], description: 'Gap between items' },
  'column-gap': { values: ['normal', 'inherit'], description: 'Column gap' },
  'row-gap': { values: ['normal', 'inherit'], description: 'Row gap' },
  'grid-template-columns': { values: ['none', 'inherit'], description: 'Grid column template' },
  'grid-template-rows': { values: ['none', 'inherit'], description: 'Grid row template' },
  'grid-column': { values: ['auto', 'inherit'], description: 'Grid column' },
  'grid-row': { values: ['auto', 'inherit'], description: 'Grid row' },
  'grid-area': { values: ['auto', 'inherit'], description: 'Grid area' },
  'font-size': { values: ['xx-small', 'x-small', 'small', 'medium', 'large', 'x-large', 'xx-large', 'smaller', 'larger', 'inherit', 'initial'], description: 'Font size' },
  'font-weight': { values: ['normal', 'bold', 'bolder', 'lighter', '100', '200', '300', '400', '500', '600', '700', '800', '900', 'inherit'], description: 'Font weight' },
  'font-family': { values: ['serif', 'sans-serif', 'monospace', 'cursive', 'fantasy', 'inherit'], description: 'Font family' },
  'font-style': { values: ['normal', 'italic', 'oblique', 'inherit'], description: 'Font style' },
  'text-align': { values: ['left', 'right', 'center', 'justify', 'inherit'], description: 'Text alignment' },
  'text-decoration': { values: ['none', 'underline', 'overline', 'line-through', 'inherit'], description: 'Text decoration' },
  'text-transform': { values: ['none', 'capitalize', 'uppercase', 'lowercase', 'inherit'], description: 'Text transform' },
  'line-height': { values: ['normal', 'inherit'], description: 'Line height' },
  'letter-spacing': { values: ['normal', 'inherit'], description: 'Letter spacing' },
  'white-space': { values: ['normal', 'nowrap', 'pre', 'pre-wrap', 'pre-line', 'inherit'], description: 'White space handling' },
  'overflow': { values: ['visible', 'hidden', 'scroll', 'auto', 'inherit'], description: 'Overflow handling' },
  'overflow-x': { values: ['visible', 'hidden', 'scroll', 'auto', 'inherit'], description: 'Horizontal overflow' },
  'overflow-y': { values: ['visible', 'hidden', 'scroll', 'auto', 'inherit'], description: 'Vertical overflow' },
  'border': { values: ['none', 'inherit', 'initial'], description: 'Border shorthand' },
  'border-width': { values: ['thin', 'medium', 'thick', 'inherit'], description: 'Border width' },
  'border-style': { values: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', 'inherit'], description: 'Border style' },
  'border-color': { values: ['transparent', 'inherit', 'initial'], description: 'Border color' },
  'border-radius': { values: ['inherit', 'initial'], description: 'Border radius' },
  'border-collapse': { values: ['collapse', 'separate', 'inherit'], description: 'Border collapse' },
  'box-shadow': { values: ['none', 'inherit', 'initial'], description: 'Box shadow' },
  'opacity': { values: ['0', '0.5', '1', 'inherit'], description: 'Opacity' },
  'cursor': { values: ['auto', 'default', 'pointer', 'wait', 'text', 'move', 'not-allowed', 'crosshair', 'help', 'inherit'], description: 'Cursor type' },
  'z-index': { values: ['auto', '0', '1', '-1', 'inherit'], description: 'Z-index' },
  'visibility': { values: ['visible', 'hidden', 'collapse', 'inherit'], description: 'Visibility' },
  'transform': { values: ['none', 'inherit', 'initial'], description: 'Transform' },
  'transition': { values: ['none', 'all', 'inherit'], description: 'Transition shorthand' },
  'transition-duration': { values: ['0s', '0.15s', '0.2s', '0.3s', '0.5s', '1s', 'inherit'], description: 'Transition duration' },
  'transition-timing-function': { values: ['ease', 'ease-in', 'ease-out', 'ease-in-out', 'linear', 'step-start', 'step-end', 'inherit'], description: 'Transition timing' },
  'animation': { values: ['none', 'inherit'], description: 'Animation shorthand' },
  'list-style': { values: ['none', 'disc', 'circle', 'square', 'decimal', 'inherit'], description: 'List style' },
  'outline': { values: ['none', 'inherit', 'initial'], description: 'Outline shorthand' },
  'outline-style': { values: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'inherit'], description: 'Outline style' },
  'outline-width': { values: ['thin', 'medium', 'thick', 'inherit'], description: 'Outline width' },
  'outline-color': { values: ['transparent', 'inherit', 'initial'], description: 'Outline color' },
  'box-sizing': { values: ['content-box', 'border-box', 'inherit'], description: 'Box sizing' },
  'float': { values: ['none', 'left', 'right', 'inherit'], description: 'Float' },
  'clear': { values: ['none', 'left', 'right', 'both', 'inherit'], description: 'Clear' },
  'pointer-events': { values: ['auto', 'none', 'inherit'], description: 'Pointer events' },
  'user-select': { values: ['auto', 'none', 'text', 'all', 'inherit'], description: 'User select' },
  'object-fit': { values: ['fill', 'contain', 'cover', 'none', 'scale-down', 'inherit'], description: 'Object fit' },
  'object-position': { values: ['center', 'top', 'bottom', 'left', 'right', 'inherit'], description: 'Object position' },
  'word-break': { values: ['normal', 'break-all', 'keep-all', 'inherit'], description: 'Word break' },
  'overflow-wrap': { values: ['normal', 'break-word', 'anywhere', 'inherit'], description: 'Overflow wrap' },
  'text-overflow': { values: ['clip', 'ellipsis', 'inherit'], description: 'Text overflow' },
  'resize': { values: ['none', 'both', 'horizontal', 'vertical', 'inherit'], description: 'Resize' },
  'vertical-align': { values: ['baseline', 'top', 'middle', 'bottom', 'text-top', 'text-bottom', 'sub', 'super', 'inherit'], description: 'Vertical alignment' },
  'direction': { values: ['ltr', 'rtl', 'inherit'], description: 'Text direction' },
  'tab-size': { values: ['2', '4', '8', 'inherit'], description: 'Tab size' },
  'filter': { values: ['none', 'inherit', 'initial'], description: 'CSS filter' },
  'clip-path': { values: ['none', 'inherit'], description: 'Clip path' },
};

// Global JS identifiers that are always available (never flag as undefined)

export const GLOBAL_JS_IDENTIFIERS = new Set([
  'window', 'document', 'console', 'Math', 'JSON', 'Object', 'Array', 'String', 'Number', 'Boolean',
  'Date', 'Promise', 'Symbol', 'RegExp', 'Error', 'TypeError', 'Map', 'Set', 'WeakMap', 'WeakSet',
  'undefined', 'null', 'true', 'false', 'NaN', 'Infinity', 'globalThis', 'fetch', 'setTimeout',
  'setInterval', 'clearTimeout', 'clearInterval', 'requestAnimationFrame', 'cancelAnimationFrame',
  'URL', 'URLSearchParams', 'FormData', 'Blob', 'File', 'FileReader', 'Headers', 'Request', 'Response',
  'Intl', 'structuredClone', 'queueMicrotask', 'atob', 'btoa', 'location', 'navigator', 'history',
  'localStorage', 'sessionStorage', 'getComputedStyle', 'alert', 'confirm', 'prompt', 'parseInt',
  'parseFloat', 'isNaN', 'isFinite', 'encodeURI', 'encodeURIComponent', 'decodeURI', 'decodeURIComponent',
]);

export function isKnownGlobal(name: string): boolean {
  return GLOBAL_JS_IDENTIFIERS.has(name) || VESK_INTRINSICS.some(i => i.name === name);
}

export const COMPLETION_GLOBALS: { name: string; detail: string }[] = [
  { name: 'console', detail: 'Debug console' },
  { name: 'window', detail: 'Global window object' },
  { name: 'document', detail: 'DOM document' },
  { name: 'Math', detail: 'Math utilities' },
  { name: 'JSON', detail: 'JSON parse/stringify' },
  { name: 'Object', detail: 'Object utilities' },
  { name: 'Array', detail: 'Array utilities' },
  { name: 'String', detail: 'String utilities' },
  { name: 'Number', detail: 'Number utilities' },
  { name: 'Boolean', detail: 'Boolean wrapper' },
  { name: 'Date', detail: 'Date utility' },
  { name: 'Promise', detail: 'Promise constructor' },
  { name: 'Map', detail: 'Map collection' },
  { name: 'Set', detail: 'Set collection' },
  { name: 'fetch', detail: 'Global fetch API' },
  { name: 'parseInt', detail: 'Parse string to integer' },
  { name: 'parseFloat', detail: 'Parse string to float' },
  { name: 'setTimeout', detail: 'Schedule a timeout' },
  { name: 'setInterval', detail: 'Schedule an interval' },
  { name: 'clearTimeout', detail: 'Cancel a timeout' },
  { name: 'clearInterval', detail: 'Cancel an interval' },
  { name: 'encodeURI', detail: 'Encode a URI' },
  { name: 'decodeURI', detail: 'Decode a URI' },
];

export const NAMED_COLORS: Record<string, [number, number, number]> = {
  red: [255, 0, 0], green: [0, 128, 0], blue: [0, 0, 255], white: [255, 255, 255],
  black: [0, 0, 0], gray: [128, 128, 128], yellow: [255, 255, 0], orange: [255, 165, 0],
  purple: [128, 0, 128], pink: [255, 192, 203], brown: [165, 42, 42], cyan: [0, 255, 255],
  magenta: [255, 0, 255], transparent: [0, 0, 0],
};
