// Canonical shared types live in @vesk/types — re-exported here so existing
// `@vesk/adapter/src/types` imports keep working. Do not redeclare shapes
// locally; add new public framework types to @vesk/types instead.
export type {
  RouteNode,
  ApiRouteNode,
  VeskPlugin,
  VeskSecurity,
  VeskCors,
  VeskRateLimit,
  VeskSecurityPreset,
  SecurityConfig,
  MiddlewareChainItem,
  MiddlewareExtractResult,
  AncestorLayout,
  BuildOptions,
  DevServerOptions,
  ProdServerOptions,
  SsrFunctionOptions,
  ApiFunctionOptions,
  ClientBundleOptions,
  ClientBundleFileEntry,
  ClientBundleCache,
  ChunkEntry,
  ClientBundleResult,
  MonolithicBundleParts,
  Manifest,
  ManifestRouteEntry,
  ManifestActionEntry,
  ManifestPrerenderedEntry,
  SsgRouteResult,
  BuildResult,
  ImageRef,
  ImageResult,
  SeoCheckIssue,
  SeoAuditResult,
  CombinedPageInfo,
  Tracked,
  Resource,
  UseFetchOptions,
  UseFetchStreamOptions,
  VeskRequest,
  VeskResponse,
  SetCookieOptions,
  CookieStore,
  ServerRequest,
  SsrDataSink,
  MdProps,
  MdConfig,
  MdHtmlMode,
  MarkdownOptions,
  MdHtmlWarning,
} from '@vesk/types';
